services:
    bruno_mcp:
        image: pmartz/bruno-mcp:latest
        container_name: bruno_mcp
        stdin_open: true
        tty: true
        environment:
            NODE_ENV: production
        volumes:
            - type: bind
              source: '%USERPROFILE%\Documents\bruno'
              target: /app/bruno_collections
        command: ["node", "--loader", "ts-node/esm/transpile-only", "src/index.ts"]
